name: 'Release'

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release
          client-payload: |
            {"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "${{ github.event.release.tag_name }}"}
